[package]
name = "sigbot"
version = "0.1.0"
edition = "2021"
authors = [ "Kaspar Schleiser <kaspar@schleiser.de>" ]

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
bincode = "1.3.3"
camino = "1.1.4"
clap = { version = "4.3.0", features = ["cargo"] }
console-subscriber = "0.1.9"
dasp = { version = "0.11.0", features = ["signal", "ring_buffer", "interpolate-sinc", "interpolate"] }
env_logger = "0.10.0"
flume = { version = "0.10.14", features = ["async"] }
futures = "0.3.28"
jammdb = "0.9.0"
log = "0.4.18"
num_cpus = "1.15.0"
once_cell = "1.17.2"
presage = { git = "https://github.com/whisperfish/presage" }
presage-store-sled = { git = "https://github.com/whisperfish/presage" }
qr2term = "0.3.1"
redlux = "0.6.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
shellexpand = "3.1.0"
tokio = { version = "1.28.2", features = ["rt-multi-thread"] }
url = "2.4.0"
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs" }

[features]
opencl = [ "whisper-rs/opencl" ]

[patch.crates-io]
"curve25519-dalek" = { git = "https://github.com/signalapp/curve25519-dalek", branch = "lizard2" }
