[package]
name = "sigbot"
version = "0.1.0"
edition = "2021"
authors = [ "Kaspar Schleiser <kaspar@schleiser.de>" ]

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
camino = "1.1.4"
console-subscriber = "0.1.8"
dasp = { version = "0.11.0", features = ["signal", "ring_buffer", "interpolate-sinc", "interpolate"] }
env_logger = "0.10.0"
flume = { version = "0.10.14", features = ["async"] }
futures = "0.3.28"
log = "0.4.17"
num_cpus = "1.15.0"
presage = { git = "https://github.com/whisperfish/presage" }
presage-store-sled = { git = "https://github.com/whisperfish/presage" }
qr2term = "0.3.1"
redlux = "0.6.0"
shellexpand = "3.1.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
whisper-rs = "0.6.0"

[patch.crates-io]
"curve25519-dalek" = { git = "https://github.com/signalapp/curve25519-dalek", branch = "lizard2" }
