name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
    - name: build deps
      run: sudo apt-get update && sudo apt-get -y install libclblast-dev --no-install-recommends
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
